### ISSUE TITLE
Captions don't work

### ISSUE THREAD

**Issue by RunasSudo** [vadmium/python-iview#20]
iview-cli attempts to download `http://www.abc.net.au/iview/captions/_video/checkout_03_12_650000.xml` instead of `http://cdn.iview.abc.net.au/cc/checkout_03_12.xml`.

(A workaround is to save `checkout_03_12.xml` to a folder, e.g. `/tmp`, then run `iview-cli -c /tmp -t checkout_03_12.mp4`.)

**Comment by vadmium** [comment]
I knew that subtitles were broken and I’m sorry I haven’t fixed it yet. Looking into it now.

Automatically getting the right file name may be a bit tricky, but certainly doable. E.g. for _video/news_DRMs_Tx_2606_650000.mp4:

* Original XML format, URL derived from older (2014) file name still works: `http://www.abc.net.au/iview/captions/news/DRMs_Tx_2606.xml` → text/xml
* Via `http://iview.abc.net.au/api/programs/drum/NU1505H115S00`:
  * `http://iview.abc.net.au/cc/legacy/news_drms_tx_2606.vtt` → application/octet-stream, uses \<br> and unencoded &
  * `http://iview.abc.net.au/cc/news_drms_tx_2606.vtt` → application/octet-stream, uses newline and \&amp;
  * `http://iview.abc.net.au/cc/news_drms_tx_2606.xml` → text/xml; charset=utf-8, identical to old XML!

I think it would be best to keep converting the subtitles to SRT. The VTT format does seem to be supported by some video players, but not older ones, and in others I found it to be buggy.

@RunasSudo, I’m curious where you saw the reference to cdn.iview.abc.net.au rather than plain iview.abc.net.au. My ISP is TPG which is metered; perhaps they change the URL if it is unmetered.

**Comment by RunasSudo** [comment]
@vadmium I got `cdn.iview.abc.net.au/cc/...` from the FireBug HTTP traffic monitor when using the iView website. The old `abc.net.au/iview/captions/...` URL also works for me.

**Comment by vadmium** [comment]
Okay. I haven’t installed Flash, so I have to rely on what others say, or poke inside the Flash, Android, etc code (where I saw no mention of the cdn URL).

Anyway, I pushed a quick fix (revision f0981c8). Ideally I would do it differently by getting the actual URL from the API, but hopefully this works for the time being. Let me know if you find a programme where it should work but doesn’t, or have any other suggestions.
